package com.itheima.crm.cxf;

import org.apache.cxf.configuration.security.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2017-12-26T15:38:59.563+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://service.crm.itheima.com/", name = "CustomerService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerService {

    @RequestWrapper(localName = "assignCustomers2FixedArea", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.cxf.AssignCustomers2FixedArea")
    @WebMethod
    @ResponseWrapper(localName = "assignCustomers2FixedAreaResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.cxf.AssignCustomers2FixedAreaResponse")
    public void assignCustomers2FixedArea(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.util.List<Integer> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCustomersNotAssociation", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.cxf.FindCustomersNotAssociation")
    @WebMethod
    @ResponseWrapper(localName = "findCustomersNotAssociationResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.cxf.FindCustomersNotAssociationResponse")
    public java.util.List<Customer> findCustomersNotAssociation();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCustomersHasAssociation", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.cxf.FindCustomersHasAssociation")
    @WebMethod
    @ResponseWrapper(localName = "findCustomersHasAssociationResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.cxf.FindCustomersHasAssociationResponse")
    public java.util.List<Customer> findCustomersHasAssociation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.cxf.FindAll")
    @WebMethod
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.cxf.FindAllResponse")
    public java.util.List<Customer> findAll();
}
