package com.itheima.bos.service.take_delivery;

import com.itheima.bos.domain.take_delivery.Order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.naming.spi.ObjectFactory;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2018-01-06T16:40:41.867+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://take_delivery.service.bos.itheima.com/", name = "OrderService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderService {

    @RequestWrapper(localName = "autoOrder", targetNamespace = "http://take_delivery.service.bos.itheima.com/", className = "com.itheima.bos.service.take_delivery.AutoOrder")
    @WebMethod
    @ResponseWrapper(localName = "autoOrderResponse", targetNamespace = "http://take_delivery.service.bos.itheima.com/", className = "com.itheima.bos.service.take_delivery.AutoOrderResponse")
    public void autoOrder(
            @WebParam(name = "arg0", targetNamespace = "")
                    Order arg0
    );
}
